basic ruby functionality
minio/minio-ruby pull request #5
Opened 2019-04-14 11:06 UTC by mbobin

2019-04-14 19:36 UTC, harshavardhana requested changes
Thanks a lot, wonderful changes. I have few comments..

2019-04-14 19:36 UTC, harshavardhana commented on minio/lib/minio/config.rb
> +      @service    = args[:service] || 's3'
service is not configurable since this is an S3 client.

2019-04-14 19:36 UTC, harshavardhana commented on minio/lib/minio/config.rb
> +      @endpoint   = args[:endpoint] || 'http://localhost:9000'
the endpoint shouldn't be of form `http://<hostname>:<port>` you should take endpoint of form `<hostname>:<port>` and avoid taking `<port>` as a special argument.

2019-04-15 18:10 UTC, harshavardhana approved these changes

2019-04-15 21:54 UTC, deekoder approved these changes

2019-04-15 21:55 UTC, merged

2019-04-15 21:56 UTC, deekoder commented
@mbobin great contribution, we'd love to send you a MinIO t-shirt. Could you come to our slack channel https://slack.min.io/

2019-04-17 17:44 UTC, mbobin commented
Awesome! Thank you!

What would be the next steps? Other functionality?